name: DOC-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
  workflow_dispatch:
  
env:
  PROJECT: DocFlow 

defaults:
    run:
      working-directory: ./doc

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      # Выдать разрешение на запись учетке GITHUB_TOKEN.
      contents: write

    steps:
      - name: Получение последней версии
        uses: actions/checkout@v3
      
      - name: Скопировать файл arc-template.md с новым именем PROJECT-ARC.md, где PROJECT - реальное имя проекта.
        run: |
          cp arc-template.md ${{PROJECT}}-arc.md
      
      # - name: Заменить плейсхолдеры в PROJECT-ARC.md на содержимое разделов из папки doc.

      # - name: Создать PROJ-ARC.pdf на основе .md
      
      - name: Коммит созданных файлов.
        uses: stefanzweifel/git-auto-commit-action@v4
