name: DOC-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
  workflow_dispatch:
  
env:
  PROJECT: DocFlow 

defaults:
    run:
      working-directory: ./doc

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      # Выдать разрешение на запись учетке GITHUB_TOKEN.
      contents: write

    steps:
      - name: Получение последней версии
        uses: actions/checkout@v3
      
      - name: Скопировать файл arc-template.md с новым именем PROJECT-ARC.md, где PROJECT - реальное имя проекта.
        run: |
          cp arc-template.md $PROJECT-arc.md
      
      - name: Заменить плейсхолдеры в PROJECT-ARC.md на содержимое разделов из папки doc.
        run: echo "Replace"
        
      - name: Install Node.js (version 10, not higher!)
        uses: actions/setup-node@v2
        with: { node-version: '10' }
      - name: Install Gitbook CLI client (gitbook-cli)
        run: npm install -g gitbook-cli
      - name: Install Gitbook plugins (gitbook install)
        run: gitbook install
      - name: Build the book to the `_book` folder (git build)
        run: gitbook build . --log=debug --debug
        
      # - name: Создать PROJ-ARC.pdf на основе .md
      
      - name: Коммит созданных файлов.
        uses: stefanzweifel/git-auto-commit-action@v4        
